import json
from app.database import SessionLocal
from app.models.hotel import Hotel


HOTELS_DATA = [
    {
        "public_id": "h001", "name": "The Nairobi Grand", "location": "Westlands, Nairobi",
        "country": "Kenya", "city": "Nairobi", "emoji": "castle", "badge": "Top Pick",
        "price_per_night": 420, "rating": 4.9, "reviews_count": 1284, "stars": 5,
        "hotel_type": "Hotel",
        "description": "A landmark of understated luxury rising above the Westlands skyline.",
        "check_in": "14:00", "check_out": "12:00",
        "pets_allowed": False, "smoking": False,
        "cancellation_policy": "free_cancellation", "lat": -1.2638, "lng": 36.8076,
        "images": ["https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800", "https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800", "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800"],
        "rooms": [{"type": "Deluxe King","pricePerNight": 420,"maxGuests": 2,"available": 5},{"type": "Executive Suite","pricePerNight": 630,"maxGuests": 3,"available": 3},{"type": "Presidential Penthouse","pricePerNight": 1020,"maxGuests": 4,"available": 1}],
        "amenities": ["Swimming Pool","Free WiFi","Gym","Breakfast","Spa","Restaurant","Bar"],
        "payments": ["Visa","Mastercard","MPESA"],
    },
    {
        "public_id": "h002", "name": "Savanna Boutique Hotel", "location": "Karen, Nairobi",
        "country": "Kenya", "city": "Nairobi", "emoji": "leaf", "badge": "Eco Friendly",
        "price_per_night": 248, "rating": 4.7, "reviews_count": 843, "stars": 4,
        "hotel_type": "Boutique",
        "description": "Nestled in Karen's leafy suburb, Savanna Boutique is a solar-powered haven.",
        "check_in": "14:00", "check_out": "11:00",
        "pets_allowed": True, "smoking": False,
        "cancellation_policy": "free_cancellation", "lat": -1.3187, "lng": 36.7103,
        "images": ["https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800", "https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?w=800"],
        "rooms": [{"type": "Garden Room","pricePerNight": 248,"maxGuests": 2,"available": 4},{"type": "Terrace Suite","pricePerNight": 330,"maxGuests": 2,"available": 2}],
        "amenities": ["Free WiFi","Breakfast","Parking","Restaurant","Pet Friendly"],
        "payments": ["Visa","Mastercard","MPESA"],
    },
    {
        "public_id": "h003", "name": "Kizingo Sky Suites", "location": "Kilimani, Nairobi",
        "country": "Kenya", "city": "Nairobi", "emoji": "city", "badge": "New",
        "price_per_night": 315, "rating": 4.8, "reviews_count": 378, "stars": 5,
        "hotel_type": "Hotel",
        "description": "Kizingo redefines the Nairobi city-break with floor-to-ceiling glass.",
        "check_in": "15:00", "check_out": "12:00",
        "pets_allowed": False, "smoking": False,
        "cancellation_policy": "partial_refund", "lat": -1.2864, "lng": 36.7857,
        "images": ["https://images.unsplash.com/photo-1590490360182-c33d57733427?w=800", "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=800", "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800"],
        "rooms": [{"type": "Studio Suite","pricePerNight": 315,"maxGuests": 2,"available": 6},{"type": "Sky Loft","pricePerNight": 510,"maxGuests": 3,"available": 2},{"type": "Corner Penthouse","pricePerNight": 780,"maxGuests": 4,"available": 1}],
        "amenities": ["Swimming Pool","Free WiFi","Gym","Bar","Room Service","Conference"],
        "payments": ["Visa","Mastercard","Amex","MPESA"],
    },
    {
        "public_id": "h004", "name": "Rift Valley Lodge", "location": "Limuru Road, Nairobi",
        "country": "Kenya", "city": "Nairobi", "emoji": "mountain", "badge": None,
        "price_per_night": 480, "rating": 4.6, "reviews_count": 561, "stars": 5,
        "hotel_type": "Resort",
        "description": "Set on 14 acres of highland forest on the city's edge.",
        "check_in": "14:00", "check_out": "11:00",
        "pets_allowed": False, "smoking": False,
        "cancellation_policy": "partial_refund", "lat": -1.1667, "lng": 36.6167,
        "images": ["https://images.unsplash.com/photo-1540541338287-41700207dee6?w=800", "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800"],
        "rooms": [{"type": "Standard Room","pricePerNight": 480,"maxGuests": 2,"available": 8},{"type": "Premium Lodge","pricePerNight": 720,"maxGuests": 3,"available": 4}],
        "amenities": ["Swimming Pool","Free WiFi","Breakfast","Spa","Restaurant","Airport Shuttle","Parking"],
        "payments": ["Visa","Mastercard","MPESA"],
    },
    {
        "public_id": "h005", "name": "Urban Rest Nairobi", "location": "CBD, Nairobi",
        "country": "Kenya", "city": "Nairobi", "emoji": "building", "badge": "Best Value",
        "price_per_night": 134, "rating": 4.3, "reviews_count": 2109, "stars": 3,
        "hotel_type": "Hotel",
        "description": "No frills — just spotless rooms and the fastest WiFi in the CBD.",
        "check_in": "14:00", "check_out": "12:00",
        "pets_allowed": False, "smoking": False,
        "cancellation_policy": "free_cancellation", "lat": -1.2833, "lng": 36.8167,
        "images": ["https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800", "https://images.unsplash.com/photo-1505577058444-a3dab90d4253?w=800"],
        "rooms": [{"type": "Standard Single","pricePerNight": 134,"maxGuests": 1,"available": 10},{"type": "Standard Double","pricePerNight": 165,"maxGuests": 2,"available": 8}],
        "amenities": ["Free WiFi","Gym","Breakfast","Parking"],
        "payments": ["Visa","Mastercard","MPESA","Cash"],
    },
    {
        "public_id": "h006", "name": "Pangani Heritage Inn", "location": "Pangani, Nairobi",
        "country": "Kenya", "city": "Nairobi", "emoji": "mosque", "badge": None,
        "price_per_night": 195, "rating": 4.5, "reviews_count": 447, "stars": 4,
        "hotel_type": "Boutique",
        "description": "Built inside a restored 1940s colonial house with courtyard bar.",
        "check_in": "13:00", "check_out": "11:00",
        "pets_allowed": False, "smoking": False,
        "cancellation_policy": "free_cancellation", "lat": -1.272, "lng": 36.838,
        "images": ["https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?w=800", "https://images.unsplash.com/photo-1606402179428-a57976d71fa4?w=800"],
        "rooms": [{"type": "Heritage Room","pricePerNight": 195,"maxGuests": 2,"available": 5},{"type": "Colonial Suite","pricePerNight": 285,"maxGuests": 3,"available": 2}],
        "amenities": ["Free WiFi","Breakfast","Restaurant","Bar","Room Service"],
        "payments": ["Visa","Mastercard","MPESA"],
    },
    {
        "public_id": "h007", "name": "Mombasa Pearl Resort", "location": "Nyali, Mombasa",
        "country": "Kenya", "city": "Mombasa", "emoji": "beach", "badge": "Beachfront",
        "price_per_night": 368, "rating": 4.8, "reviews_count": 931, "stars": 5,
        "hotel_type": "Resort",
        "description": "White coral sand and turquoise Indian Ocean at a full-service beachfront resort.",
        "check_in": "14:00", "check_out": "11:00",
        "pets_allowed": False, "smoking": False,
        "cancellation_policy": "partial_refund", "lat": -4.0435, "lng": 39.7195,
        "images": ["https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=800", "https://images.unsplash.com/photo-1540541338287-41700207dee6?w=800", "https://images.unsplash.com/photo-1551918120-9739cb430c6d?w=800"],
        "rooms": [{"type": "Ocean View Room","pricePerNight": 368,"maxGuests": 2,"available": 6},{"type": "Beach Suite","pricePerNight": 570,"maxGuests": 3,"available": 3},{"type": "Presidential Villa","pricePerNight": 975,"maxGuests": 5,"available": 1}],
        "amenities": ["Swimming Pool","Free WiFi","Breakfast","Spa","Restaurant","Bar","Parking","Airport Shuttle"],
        "payments": ["Visa","Mastercard","Amex","MPESA"],
    },
    {
        "public_id": "h008", "name": "Diani Beach House", "location": "Diani, Kwale County",
        "country": "Kenya", "city": "Diani", "emoji": "wave", "badge": None,
        "price_per_night": 278, "rating": 4.6, "reviews_count": 302, "stars": 4,
        "hotel_type": "Boutique",
        "description": "An intimate 12-room house tucked behind a coral garden on Diani beach.",
        "check_in": "14:00", "check_out": "10:00",
        "pets_allowed": True, "smoking": False,
        "cancellation_policy": "free_cancellation", "lat": -4.3167, "lng": 39.5667,
        "images": ["https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?w=800", "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=800"],
        "rooms": [{"type": "Garden Cottage","pricePerNight": 278,"maxGuests": 2,"available": 4},{"type": "Oceanfront Villa","pricePerNight": 435,"maxGuests": 4,"available": 2}],
        "amenities": ["Swimming Pool","Free WiFi","Breakfast","Restaurant","Parking","Pet Friendly"],
        "payments": ["Visa","Mastercard","MPESA"],
    },
    {
        "public_id": "h009", "name": "Shibuya Capsule Tower", "location": "Shibuya, Tokyo",
        "country": "Japan", "city": "Tokyo", "emoji": "castle-jp", "badge": "Trending",
        "price_per_night": 180, "rating": 4.5, "reviews_count": 1642, "stars": 4,
        "hotel_type": "Boutique",
        "description": "Eighteen floors of minimalist Japanese design above Shibuya Crossing.",
        "check_in": "15:00", "check_out": "11:00",
        "pets_allowed": False, "smoking": False,
        "cancellation_policy": "free_cancellation", "lat": 35.658, "lng": 139.7016,
        "images": ["https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800", "https://images.unsplash.com/photo-1536098561742-ca998e48cbcc?w=800", "https://images.unsplash.com/photo-1566937169390-7adae16e4e2c?w=800"],
        "rooms": [{"type": "Capsule Pod","pricePerNight": 180,"maxGuests": 1,"available": 12},{"type": "Zen Suite","pricePerNight": 360,"maxGuests": 2,"available": 4},{"type": "Sky Penthouse","pricePerNight": 630,"maxGuests": 3,"available": 2}],
        "amenities": ["Free WiFi","Restaurant","Bar","Rooftop","Laundry","Concierge"],
        "payments": ["Visa","Mastercard","Amex"],
    },
    {
        "public_id": "h010", "name": "Le Rive Gauche", "location": "Saint-Germain, Paris",
        "country": "France", "city": "Paris", "emoji": "croissant", "badge": "Romantic",
        "price_per_night": 525, "rating": 4.8, "reviews_count": 2156, "stars": 5,
        "hotel_type": "Hotel",
        "description": "A quiet Saint-Germain side street hotel with creaking parquet and marble fireplaces.",
        "check_in": "15:00", "check_out": "12:00",
        "pets_allowed": True, "smoking": False,
        "cancellation_policy": "partial_refund", "lat": 48.8546, "lng": 2.3366,
        "images": ["https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800", "https://images.unsplash.com/photo-1550340499-a6c60fc8280e?w=800", "https://images.unsplash.com/photo-1453614512568-c4024d13c247?w=800"],
        "rooms": [{"type": "Classic Room","pricePerNight": 525,"maxGuests": 2,"available": 6},{"type": "Balcony Suite","pricePerNight": 870,"maxGuests": 2,"available": 3},{"type": "Penthouse Atelier","pricePerNight": 1335,"maxGuests": 4,"available": 1}],
        "amenities": ["Free WiFi","Breakfast","Bar","Room Service","Concierge","Valet Parking","Pet Friendly"],
        "payments": ["Visa","Mastercard","Amex"],
    },
    {
        "public_id": "h011", "name": "The Hudson Rest", "location": "Midtown, Manhattan",
        "country": "United States", "city": "New York", "emoji": "statue", "badge": "Top Pick",
        "price_per_night": 375, "rating": 4.6, "reviews_count": 3108, "stars": 4,
        "hotel_type": "Hotel",
        "description": "Manhattan energy with floor-to-ceiling skyline views and a Bryant Park location.",
        "check_in": "15:00", "check_out": "12:00",
        "pets_allowed": False, "smoking": False,
        "cancellation_policy": "free_cancellation", "lat": 40.7549, "lng": -73.984,
        "images": ["https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=800", "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800", "https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?w=800"],
        "rooms": [{"type": "City Room","pricePerNight": 375,"maxGuests": 2,"available": 10},{"type": "Executive King","pricePerNight": 630,"maxGuests": 2,"available": 5},{"type": "Hudson Suite","pricePerNight": 1125,"maxGuests": 4,"available": 2}],
        "amenities": ["Free WiFi","Gym","Bar","Room Service","Concierge","Business Center","Restaurant"],
        "payments": ["Visa","Mastercard","Amex"],
    },
    {
        "public_id": "h012", "name": "Harbour Glass Resort", "location": "Darling Harbour, Sydney",
        "country": "Australia", "city": "Sydney", "emoji": "kangaroo", "badge": "New",
        "price_per_night": 480, "rating": 4.9, "reviews_count": 765, "stars": 5,
        "hotel_type": "Resort",
        "description": "A shimmering glass crescent wrapped around Darling Harbour facing the Opera House.",
        "check_in": "14:00", "check_out": "11:00",
        "pets_allowed": False, "smoking": False,
        "cancellation_policy": "partial_refund", "lat": -33.8727, "lng": 151.1988,
        "images": ["https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?w=800", "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=800", "https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800"],
        "rooms": [{"type": "Harbour Room","pricePerNight": 480,"maxGuests": 2,"available": 8},{"type": "Opera View Suite","pricePerNight": 780,"maxGuests": 3,"available": 3},{"type": "Penthouse Marina","pricePerNight": 1200,"maxGuests": 4,"available": 1}],
        "amenities": ["Swimming Pool","Free WiFi","Breakfast","Gym","Restaurant","Bar","Parking","Airport Shuttle"],
        "payments": ["Visa","Mastercard","Amex"],
    },
    {
        "public_id": "h013", "name": "Table Bay Haven", "location": "Victoria & Alfred Waterfront",
        "country": "South Africa", "city": "Cape Town", "emoji": "mountain", "badge": "Beachfront",
        "price_per_night": 240, "rating": 4.7, "reviews_count": 1194, "stars": 5,
        "hotel_type": "Resort",
        "description": "Where Table Mountain meets the Atlantic at the V&A Waterfront.",
        "check_in": "14:00", "check_out": "11:00",
        "pets_allowed": False, "smoking": False,
        "cancellation_policy": "free_cancellation", "lat": -33.9036, "lng": 18.4214,
        "images": ["https://images.unsplash.com/photo-1580060839134-75a5edca2e99?w=800", "https://images.unsplash.com/photo-1573843981267-be1999ff37cd?w=800", "https://images.unsplash.com/photo-1590490359683-658d3d23f972?w=800"],
        "rooms": [{"type": "Mountain View Room","pricePerNight": 240,"maxGuests": 2,"available": 7},{"type": "Ocean Suite","pricePerNight": 420,"maxGuests": 3,"available": 4},{"type": "Presidential Villa","pricePerNight": 675,"maxGuests": 5,"available": 1}],
        "amenities": ["Swimming Pool","Free WiFi","Breakfast","Spa","Restaurant","Bar","Parking","Airport Shuttle"],
        "payments": ["Visa","Mastercard","Amex"],
    },
    {
        "public_id": "h014", "name": "Ubud Canopy Retreat", "location": "Ubud, Bali",
        "country": "Indonesia", "city": "Bali", "emoji": "palm", "badge": "Eco Friendly",
        "price_per_night": 180, "rating": 4.7, "reviews_count": 583, "stars": 4,
        "hotel_type": "Resort",
        "description": "Eleven bamboo-and-thatch villas suspended above the Ayung River gorge.",
        "check_in": "14:00", "check_out": "12:00",
        "pets_allowed": True, "smoking": False,
        "cancellation_policy": "free_cancellation", "lat": -8.525, "lng": 115.2626,
        "images": ["https://images.unsplash.com/photo-1555400038-63f5ba517a47?w=800", "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=800", "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800"],
        "rooms": [{"type": "Jungle Bungalow","pricePerNight": 180,"maxGuests": 2,"available": 5},{"type": "Rice Terrace Villa","pricePerNight": 330,"maxGuests": 3,"available": 3},{"type": "Canopy Suite","pricePerNight": 570,"maxGuests": 4,"available": 2}],
        "amenities": ["Swimming Pool","Free WiFi","Breakfast","Spa","Restaurant","Bar","Pet Friendly"],
        "payments": ["Visa","Mastercard","Amex"],
    },
    {
        "public_id": "h015", "name": "Aurora Glass Lodge", "location": "Thingvellir, Reykjavik",
        "country": "Iceland", "city": "Reykjavik", "emoji": "sparkles", "badge": "Top Pick",
        "price_per_night": 450, "rating": 4.8, "reviews_count": 621, "stars": 4,
        "hotel_type": "Boutique",
        "description": "Six glass-roofed cabins scattered across a lava field in Thingvellir National Park.",
        "check_in": "15:00", "check_out": "11:00",
        "pets_allowed": False, "smoking": False,
        "cancellation_policy": "partial_refund", "lat": 64.255, "lng": -21.1325,
        "images": ["https://images.unsplash.com/photo-1504214208698-ea1916a2195a?w=800", "https://images.unsplash.com/photo-1520769669658-f07657f5a307?w=800", "https://images.unsplash.com/photo-1531366936337-7c912a4589a7?w=800"],
        "rooms": [{"type": "Glass Cabin","pricePerNight": 450,"maxGuests": 2,"available": 4},{"type": "Lava Suite","pricePerNight": 720,"maxGuests": 3,"available": 2}],
        "amenities": ["Free WiFi","Breakfast","Spa","Restaurant","Bar","Parking","Hot Tub"],
        "payments": ["Visa","Mastercard","Amex"],
    },
    {
        "public_id": "h016", "name": "Dar Essalam Riád", "location": "Medina, Marrakech",
        "country": "Morocco", "city": "Marrakech", "emoji": "mosque", "badge": "Romantic",
        "price_per_night": 210, "rating": 4.9, "reviews_count": 847, "stars": 5,
        "hotel_type": "Boutique",
        "description": "A 300-year-old riád hidden behind an unmarked door in the Marrakech Medina.",
        "check_in": "14:00", "check_out": "12:00",
        "pets_allowed": False, "smoking": False,
        "cancellation_policy": "free_cancellation", "lat": 31.6311, "lng": -7.9885,
        "images": ["https://images.unsplash.com/photo-1597212618440-806262de4f6b?w=800", "https://images.unsplash.com/photo-1590073242678-70ee3fc28f8e?w=800", "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800"],
        "rooms": [{"type": "Courtyard Room","pricePerNight": 210,"maxGuests": 2,"available": 5},{"type": "Terrace Suite","pricePerNight": 360,"maxGuests": 2,"available": 3},{"type": "Riad Royal","pricePerNight": 600,"maxGuests": 4,"available": 1}],
        "amenities": ["Swimming Pool","Free WiFi","Breakfast","Spa","Restaurant","Bar","Airport Shuttle"],
        "payments": ["Visa","Mastercard","Cash"],
    },
    {
        "public_id": "h017", "name": "Copacabana Palace", "location": "Copacabana, Rio de Janeiro",
        "country": "Brazil", "city": "Rio de Janeiro", "emoji": "beach", "badge": "Beachfront",
        "price_per_night": 420, "rating": 4.7, "reviews_count": 1342, "stars": 5,
        "hotel_type": "Resort",
        "description": "Where Copacabana meets white marble — hosting diplomats and dreamers since 1923.",
        "check_in": "14:00", "check_out": "12:00",
        "pets_allowed": False, "smoking": False,
        "cancellation_policy": "free_cancellation", "lat": -22.9711, "lng": -43.1823,
        "images": ["https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=800", "https://images.unsplash.com/photo-1540541338287-41700207dee6?w=800", "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800"],
        "rooms": [{"type": "Ocean Room","pricePerNight": 420,"maxGuests": 2,"available": 8},{"type": "Beach Suite","pricePerNight": 675,"maxGuests": 3,"available": 4},{"type": "Presidential Suite","pricePerNight": 1080,"maxGuests": 4,"available": 1}],
        "amenities": ["Swimming Pool","Free WiFi","Breakfast","Gym","Restaurant","Bar","Airport Shuttle","Spa"],
        "payments": ["Visa","Mastercard","Amex"],
    },
    {
        "public_id": "h018", "name": "Cancún Coral Resort", "location": "Zona Hotelera, Cancún",
        "country": "Mexico", "city": "Cancún", "emoji": "palm", "badge": "Top Pick",
        "price_per_night": 330, "rating": 4.6, "reviews_count": 2018, "stars": 5,
        "hotel_type": "Resort",
        "description": "Twelve acres of white sand with turquoise cenote-style pools.",
        "check_in": "15:00", "check_out": "11:00",
        "pets_allowed": False, "smoking": False,
        "cancellation_policy": "partial_refund", "lat": 21.1619, "lng": -86.8515,
        "images": ["https://images.unsplash.com/photo-1551918120-9739cb430c6d?w=800", "https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?w=800", "https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800"],
        "rooms": [{"type": "Garden View Room","pricePerNight": 330,"maxGuests": 2,"available": 10},{"type": "Oceanfront Suite","pricePerNight": 570,"maxGuests": 3,"available": 5},{"type": "Royal Villa","pricePerNight": 900,"maxGuests": 5,"available": 2}],
        "amenities": ["Swimming Pool","Free WiFi","Breakfast","Restaurant","Bar","Spa","Parking","Airport Shuttle"],
        "payments": ["Visa","Mastercard","Amex"],
    },
    {
        "public_id": "h019", "name": "Burj Sky Hotel", "location": "Downtown Dubai",
        "country": "United Arab Emirates", "city": "Dubai", "emoji": "building", "badge": "Luxury",
        "price_per_night": 675, "rating": 4.9, "reviews_count": 987, "stars": 5,
        "hotel_type": "Hotel",
        "description": "Rising 80 storeys above the Dubai Fountain with cloud-level hospitality.",
        "check_in": "15:00", "check_out": "12:00",
        "pets_allowed": False, "smoking": False,
        "cancellation_policy": "partial_refund", "lat": 25.1972, "lng": 55.2744,
        "images": ["https://images.unsplash.com/photo-1590490360182-c33d57733427?w=800", "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800", "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800"],
        "rooms": [{"type": "Sky Room","pricePerNight": 675,"maxGuests": 2,"available": 6},{"type": "Executive Suite","pricePerNight": 1125,"maxGuests": 3,"available": 3},{"type": "Royal Penthouse","pricePerNight": 1800,"maxGuests": 5,"available": 1}],
        "amenities": ["Swimming Pool","Free WiFi","Gym","Restaurant","Bar","Room Service","Spa","Parking","Concierge"],
        "payments": ["Visa","Mastercard","Amex"],
    },
    {
        "public_id": "h020", "name": "Bangkok Spice Inn", "location": "Sukhumvit, Bangkok",
        "country": "Thailand", "city": "Bangkok", "emoji": "noodle", "badge": "Best Value",
        "price_per_night": 128, "rating": 4.4, "reviews_count": 2673, "stars": 4,
        "hotel_type": "Boutique",
        "description": "A hidden laneway off Sukhumvit Soi 11 — the Bangkok you came for.",
        "check_in": "14:00", "check_out": "12:00",
        "pets_allowed": False, "smoking": False,
        "cancellation_policy": "free_cancellation", "lat": 13.7367, "lng": 100.5603,
        "images": ["https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800", "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=800", "https://images.unsplash.com/photo-1562778612-e1e0cda9915c?w=800"],
        "rooms": [{"type": "Standard Room","pricePerNight": 128,"maxGuests": 2,"available": 14},{"type": "Deluxe Balcony","pricePerNight": 210,"maxGuests": 2,"available": 6},{"type": "Sukhumvit Suite","pricePerNight": 315,"maxGuests": 3,"available": 3}],
        "amenities": ["Free WiFi","Breakfast","Restaurant","Bar","Rooftop","Laundry","Airport Shuttle"],
        "payments": ["Visa","Mastercard","Cash"],
    },
    {
        "public_id": "h021", "name": "Udaipur Lake View", "location": "Lake Pichola, Udaipur",
        "country": "India", "city": "Udaipur", "emoji": "temple", "badge": "Romantic",
        "price_per_night": 195, "rating": 4.7, "reviews_count": 756, "stars": 5,
        "hotel_type": "Hotel",
        "description": "A converted maharaja's guesthouse floating on the edge of Lake Pichola.",
        "check_in": "14:00", "check_out": "12:00",
        "pets_allowed": False, "smoking": False,
        "cancellation_policy": "free_cancellation", "lat": 24.576, "lng": 73.678,
        "images": ["https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800", "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800", "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=800"],
        "rooms": [{"type": "Palace Room","pricePerNight": 195,"maxGuests": 2,"available": 6},{"type": "Lake View Suite","pricePerNight": 345,"maxGuests": 3,"available": 3},{"type": "Maharaja Suite","pricePerNight": 585,"maxGuests": 4,"available": 1}],
        "amenities": ["Swimming Pool","Free WiFi","Restaurant","Bar","Spa","Rooftop"],
        "payments": ["Visa","Mastercard","Amex"],
    },
    {
        "public_id": "h022", "name": "Jing'an Zen Hotel", "location": "Jing'an, Shanghai",
        "country": "China", "city": "Shanghai", "emoji": "lantern", "badge": "New",
        "price_per_night": 255, "rating": 4.5, "reviews_count": 432, "stars": 4,
        "hotel_type": "Boutique",
        "description": "Zen minimalism meets Shanghai speed in a converted lane house.",
        "check_in": "15:00", "check_out": "12:00",
        "pets_allowed": False, "smoking": False,
        "cancellation_policy": "partial_refund", "lat": 31.224, "lng": 121.448,
        "images": ["https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?w=800", "https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800", "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800"],
        "rooms": [{"type": "Zen Room","pricePerNight": 255,"maxGuests": 2,"available": 5},{"type": "Bamboo Suite","pricePerNight": 405,"maxGuests": 2,"available": 2}],
        "amenities": ["Free WiFi","Gym","Breakfast","Bar","Room Service","Concierge"],
        "payments": ["Visa","Mastercard","Alipay"],
    },
    {
        "public_id": "h023", "name": "Cromwell Gardens", "location": "South Kensington, London",
        "country": "United Kingdom", "city": "London", "emoji": "guard", "badge": "Top Pick",
        "price_per_night": 390, "rating": 4.6, "reviews_count": 1892, "stars": 4,
        "hotel_type": "Hotel",
        "description": "Victorian townhouse charm with a modern twist in the Royal Borough.",
        "check_in": "15:00", "check_out": "11:00",
        "pets_allowed": True, "smoking": False,
        "cancellation_policy": "free_cancellation", "lat": 51.494, "lng": -0.177,
        "images": ["https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800", "https://images.unsplash.com/photo-1505577058444-a3dab90d4253?w=800", "https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800"],
        "rooms": [{"type": "Classic Double","pricePerNight": 390,"maxGuests": 2,"available": 7},{"type": "Garden Suite","pricePerNight": 645,"maxGuests": 3,"available": 3}],
        "amenities": ["Free WiFi","Breakfast","Bar","Room Service","Concierge","Pet Friendly"],
        "payments": ["Visa","Mastercard","Amex"],
    },
    {
        "public_id": "h024", "name": "Dolce Vita Roma", "location": "Trastevere, Rome",
        "country": "Italy", "city": "Rome", "emoji": "pizza", "badge": "Romantic",
        "price_per_night": 285, "rating": 4.7, "reviews_count": 1123, "stars": 4,
        "hotel_type": "Boutique",
        "description": "A 17th-century palazzo with ivy-covered terrace overlooking the Tiber.",
        "check_in": "14:00", "check_out": "11:00",
        "pets_allowed": True, "smoking": False,
        "cancellation_policy": "partial_refund", "lat": 41.886, "lng": 12.469,
        "images": ["https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800", "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800", "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=800"],
        "rooms": [{"type": "Courtyard Room","pricePerNight": 285,"maxGuests": 2,"available": 5},{"type": "Terrace Suite","pricePerNight": 465,"maxGuests": 3,"available": 2}],
        "amenities": ["Free WiFi","Breakfast","Bar","Restaurant","Rooftop","Pet Friendly"],
        "payments": ["Visa","Mastercard","Cash"],
    },
    {
        "public_id": "h025", "name": "Casa Cataluña", "location": "Gothic Quarter, Barcelona",
        "country": "Spain", "city": "Barcelona", "emoji": "sun", "badge": "Best Value",
        "price_per_night": 165, "rating": 4.4, "reviews_count": 2341, "stars": 3,
        "hotel_type": "Hostel",
        "description": "A lively social hostel steps from Las Ramblas with rooftop sangria nights.",
        "check_in": "14:00", "check_out": "11:00",
        "pets_allowed": False, "smoking": False,
        "cancellation_policy": "free_cancellation", "lat": 41.382, "lng": 2.176,
        "images": ["https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?w=800", "https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800"],
        "rooms": [{"type": "Dorm Bed","pricePerNight": 45,"maxGuests": 1,"available": 20},{"type": "Private Double","pricePerNight": 165,"maxGuests": 2,"available": 4}],
        "amenities": ["Free WiFi","Breakfast","Bar","Rooftop","Laundry","Airport Shuttle"],
        "payments": ["Visa","Mastercard","Cash"],
    },
    {
        "public_id": "h026", "name": "Nile Breeze Hotel", "location": "Zamalek, Cairo",
        "country": "Egypt", "city": "Cairo", "emoji": "pyramid", "badge": None,
        "price_per_night": 150, "rating": 4.3, "reviews_count": 678, "stars": 4,
        "hotel_type": "Hotel",
        "description": "Art deco charm on the Nile with rooftop views of the citadel.",
        "check_in": "14:00", "check_out": "12:00",
        "pets_allowed": False, "smoking": False,
        "cancellation_policy": "free_cancellation", "lat": 30.064, "lng": 31.221,
        "images": ["https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800", "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800"],
        "rooms": [{"type": "Nile View Room","pricePerNight": 150,"maxGuests": 2,"available": 6},{"type": "Executive Suite","pricePerNight": 270,"maxGuests": 3,"available": 2}],
        "amenities": ["Free WiFi","Restaurant","Bar","Rooftop","Concierge","Airport Shuttle"],
        "payments": ["Visa","Mastercard","Cash"],
    },
    {
        "public_id": "h027", "name": "Santorini Cave House", "location": "Oia, Santorini",
        "country": "Greece", "city": "Santorini", "emoji": "wave", "badge": "Luxury",
        "price_per_night": 540, "rating": 4.9, "reviews_count": 435, "stars": 5,
        "hotel_type": "Boutique",
        "description": "A whitewashed cave carved into the caldera cliff with a private infinity pool.",
        "check_in": "15:00", "check_out": "11:00",
        "pets_allowed": False, "smoking": False,
        "cancellation_policy": "non_refundable", "lat": 36.461, "lng": 25.376,
        "images": ["https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=800", "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800"],
        "rooms": [{"type": "Caldera Cave","pricePerNight": 540,"maxGuests": 2,"available": 3},{"type": "Sunset Suite","pricePerNight": 870,"maxGuests": 2,"available": 2}],
        "amenities": ["Swimming Pool","Free WiFi","Breakfast","Spa","Restaurant","Bar","Airport Shuttle"],
        "payments": ["Visa","Mastercard","Amex"],
    },
    {
        "public_id": "h028", "name": "Marina Bay Sanctuary", "location": "Marina Bay, Singapore",
        "country": "Singapore", "city": "Singapore", "emoji": "merlion", "badge": "Top Pick",
        "price_per_night": 510, "rating": 4.8, "reviews_count": 1567, "stars": 5,
        "hotel_type": "Hotel",
        "description": "Where futuristic architecture meets tropical greenery at the heart of Marina Bay.",
        "check_in": "15:00", "check_out": "12:00",
        "pets_allowed": False, "smoking": False,
        "cancellation_policy": "partial_refund", "lat": 1.283, "lng": 103.859,
        "images": ["https://images.unsplash.com/photo-1562778612-e1e0cda9915c?w=800", "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800", "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800"],
        "rooms": [{"type": "Sky View Room","pricePerNight": 510,"maxGuests": 2,"available": 8},{"type": "Executive Suite","pricePerNight": 825,"maxGuests": 3,"available": 4},{"type": "Presidential Suite","pricePerNight": 1350,"maxGuests": 4,"available": 1}],
        "amenities": ["Swimming Pool","Free WiFi","Gym","Breakfast","Spa","Restaurant","Bar","Concierge"],
        "payments": ["Visa","Mastercard","Amex"],
    },
]


def seed_database():
    from app.database import SessionLocal
    db = SessionLocal()
    try:
        if db.query(Hotel).count() > 0:
            print("Database already seeded, skipping")
            return
        for data in HOTELS_DATA:
            hotel = Hotel(**data)
            db.add(hotel)
        db.commit()
        print(f"Seeded {len(HOTELS_DATA)} hotels")
    finally:
        db.close()
